highlighter: pygments
markdown: kramdown
uikernel_version: 1.0.0
github: https://github.com/softindex/uikernel/tree/master/
github_uikernel: https://github.com/softindex/uikernel
exclude:
  - Gemfile
  - params.json
  - gulpfile.js
  - npm-*
  - package.json
  - guide/**/src
defaults:
  - scope:
      path: docs
      type: pages
    values:
      layout: docs
